#!/bin/sh

clear

rm bin/compiled

python3 preprocessor.py

cd bin

nasm -f elf64 output.asm -o asm.o

gcc -c -g -Wall -m64 ../src/long_mode_os/**/*.c -I ../src/long_mode_os/global_includes/ -I ../src/long_mode_os/kernel/ -I ../src/long_mode_os/kernel/memory/ -I ../src/long_mode_os/drivers/ -nostdlib -ffreestanding -mno-red-zone -fno-exceptions -nodefaultlibs -fno-builtin -fno-pic && touch compiled

ld -m elf_x86_64 -static -nostdlib -T ../linker.ld *.o -o os.img

mv font.o font.o.preserve
rm *.o
mv font.o.preserve font.o

mkisofs -no-emul-boot -input-charset utf-8 -boot-load-size 10 -exclude-list ../exclude.txt -o os.iso -b os.img .

truncate -s 1M os.img

cd ..

